services:
  - type: web
    name: passport-photo-maker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python -c \"from rembg import new_session; new_session('u2netp')\""
    startCommand: "gunicorn app:app --timeout 120 --workers 1"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9